-- apagar os dados das tabelas
DELETE FROM ACESSO; 
DELETE FROM ALBUM; 
DELETE FROM ALBUM_TEMP; 
DELETE FROM AMIZADE; 
DELETE FROM AMIZADE_TEMP; 
DELETE FROM ATUALIZACOES; 
DELETE FROM CATEGORIA; 
DELETE FROM COMENTARIO; 
DELETE FROM COMPOE; 
DELETE FROM COMUNIDADE; 
DELETE FROM CONTA; 
DELETE FROM EMAIL; 
DELETE FROM FOTO; 
DELETE FROM FOTO_TEMP; 
DELETE FROM GRUPO; 
DELETE FROM INTERAGE; 
DELETE FROM OBJETO; 
DELETE FROM PARTICIPA; 
DELETE FROM POST; 
DELETE FROM POST_TEMP; 
DELETE FROM TELEFONE; 
DELETE FROM USUARIO; 



DROP TABLE ACESSO CASCADE CONSTRAINTS PURGE; 
DROP TABLE ALBUM CASCADE CONSTRAINTS PURGE; 
DROP TABLE ALBUM_TEMP CASCADE CONSTRAINTS PURGE; 
DROP TABLE AMIZADE CASCADE CONSTRAINTS PURGE; 
DROP TABLE AMIZADE_TEMP CASCADE CONSTRAINTS PURGE; 
DROP TABLE ATUALIZACOES CASCADE CONSTRAINTS PURGE; 
DROP TABLE CATEGORIA CASCADE CONSTRAINTS PURGE; 
DROP TABLE COMENTARIO CASCADE CONSTRAINTS PURGE; 
DROP TABLE COMPOE CASCADE CONSTRAINTS PURGE; 
DROP TABLE COMUNIDADE CASCADE CONSTRAINTS PURGE; 
DROP TABLE CONTA CASCADE CONSTRAINTS PURGE; 
DROP TABLE EMAIL CASCADE CONSTRAINTS PURGE; 
DROP TABLE FOTO CASCADE CONSTRAINTS PURGE; 
DROP TABLE FOTO_TEMP CASCADE CONSTRAINTS PURGE; 
DROP TABLE GRUPO CASCADE CONSTRAINTS PURGE; 
DROP TABLE INTERAGE CASCADE CONSTRAINTS PURGE; 
DROP TABLE OBJETO CASCADE CONSTRAINTS PURGE; 
DROP TABLE PARTICIPA CASCADE CONSTRAINTS PURGE; 
DROP TABLE POST CASCADE CONSTRAINTS PURGE; 
DROP TABLE POST_TEMP CASCADE CONSTRAINTS PURGE; 
DROP TABLE TELEFONE CASCADE CONSTRAINTS PURGE; 
DROP TABLE USUARIO CASCADE CONSTRAINTS PURGE; 

DROP VIEW view_community PURGE; 

DROP SEQUENCE SEQIDUSUARIO;
DROP SEQUENCE SEQIDOBJETO;
DROP SEQUENCE SEQIDAMIZADE;
DROP SEQUENCE SEQIDATUALIZACOES;


DROP PACKAGE PACKCOMMUNITY; 
DROP PACKAGE PACKFRIENDS; 
DROP PACKAGE PACKGROUPS; 
DROP PACKAGE PACKINICIALPAGE; 
DROP PACKAGE PACKLOGIN; 
DROP PACKAGE PACKPHOTO; 
DROP PACKAGE PACKPOST; 
DROP PACKAGE PACKUSER; 


DROP TRIGGER ADDUSERCOMMUNITY; 
DROP TRIGGER GROUPUSER;
DROP TRIGGER REMOVEUSERCOMMUNITY;
DROP TRIGGER TALBUM;
DROP TRIGGER TALBUMTEMP;
DROP TRIGGER TAMIZADE;
DROP TRIGGER TAMIZADETEMP;
DROP TRIGGER TCOMENTARIO;
DROP TRIGGER TFOTO;
DROP TRIGGER TFOTOTEMP;
DROP TRIGGER TPOST;
DROP TRIGGER TPOSTTEMP;


DROP TYPE USER_T FORCE;
DROP TYPE USERS FORCE; 
DROP TYPE ALBUM_T FORCE; 
DROP TYPE ALBUMS FORCE;
DROP TYPE AMIGOOS FORCE;
DROP TYPE COMMENT_T FORCE;
DROP TYPE COMMENTS FORCE;
DROP TYPE COMMUNITY_T FORCE;
DROP TYPE COMMUNITYS FORCE;
DROP TYPE EMAILS FORCE;
DROP TYPE FRIEND_T FORCE;
DROP TYPE FRIENDS FORCE;
DROP TYPE GROUP_T FORCE;
DROP TYPE GROUPOOS FORCE;
DROP TYPE GRUPOS FORCE;
DROP TYPE INICIAL_COMMUNITY_T FORCE;
DROP TYPE INICIAL_COMMUNITYS FORCE;
DROP TYPE LOGS FORCE;
DROP TYPE PHOTO_T FORCE;
DROP TYPE PHOTOS FORCE;
DROP TYPE POST_T FORCE;
DROP TYPE POSTS FORCE;
DROP TYPE TELEFONES FORCE;
DROP TYPE UPDATES; FORCE 


